# Generated by Django 4.0.1 on 2022-01-27 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0011_registrationdata_alter_news_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 27, 12, 9, 12, 992001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sportnews',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 27, 12, 9, 13, 8310, tzinfo=utc)),
        ),
    ]
