# Generated by Django 4.0.1 on 2022-02-10 17:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0013_publication_alter_news_pub_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 10, 17, 48, 44, 131831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sportnews',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 10, 17, 48, 44, 148787, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TheArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('pub_date', models.CharField(max_length=30)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsApp.reporter')),
            ],
            options={
                'ordering': ('headline',),
            },
        ),
    ]
