# Generated by Django 4.0.1 on 2022-02-11 09:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0015_place_alter_news_pub_date_alter_sportnews_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 11, 9, 7, 34, 566083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sportnews',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 11, 9, 7, 34, 583239, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
