# Generated by Django 4.0.1 on 2022-02-11 18:14

import datetime
import django.contrib.auth.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('NewsApp', '0020_burgerbar_myplace_alter_news_pub_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'ordering': ('username',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 11, 18, 14, 1, 780053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sportnews',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 11, 18, 14, 1, 780338, tzinfo=utc)),
        ),
    ]
